#ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"


Vagrant.configure("2") do |config|
    #******** настройка сераера ************
        #**** первичная конфигурация сервера ****
        config.vm.define "nfs-server" do |server|
        server.vm.box = "centos/7"
        server.vm.provider "virtualbox" do |vb|
        vb.memory = 256
        vb.cpus = 1
        vb.name = "nfs-server"
    end
        #**** установка ПО сервера и необходимых параметров ****
        server.vm.hostname = "nfs-server"
        server.vm.network "private_network", intnet: "inet", type:"static",  ip: "192.168.56.10"
        server.vm.synced_folder ".", "/vagrant",  
          type: "rsync",
          rsync_auto: "true",
          rsync_exclude: [".git/",".vagrant/",".gitignore","Vagrantfile"]
        server.vm.provision "shell", inline: <<-SHELL
        yum install -y nfs-utils
        SHELL
        server.vm.provision "shell", path: "server.sh"
    end
    
# ********** Настройка склиенской машины ************
         #**** первичная конфигурация клиента ****
        config.vm.define "nfs-client" do |client|
        client.vm.box = "centos/7"
        client.vm.provider "virtualbox" do |vb|
        vb.memory = 256
        vb.cpus = 1
        vb.name = "nfs-client"
    end
        #**** установка ПО клиента и необходимых параметров ****
        client.vm.hostname = "nfs-client"
        client.vm.network "private_network", intnet: "inet", type:"static",  ip: "192.168.56.11"
        client.vm.synced_folder ".", "/vagrant",  
        type: "rsync",
        rsync_auto: "true",
        rsync_exclude: [".git/",".vagrant/",".gitignore","Vagrantfile"]
        client.vm.provision "shell", inline: <<-SHELL
        yum install -y nfs-utils
        SHELL
        client.vm.provision "shell", path: "client.sh"
    end
end 